# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.DecimalField(blank=True, decimal_places=1, max_digits=5, primary_key=True, serialize=False)),
                ('color', models.CharField(blank=True, max_length=16, null=True)),
                ('director_name', models.CharField(blank=True, max_length=32, null=True)),
                ('num_critic_for_reviews', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('duration', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('director_facebook_likes', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('actor_3_facebook_likes', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('actor_2_name', models.CharField(blank=True, max_length=28, null=True)),
                ('actor_1_facebook_likes', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('gross', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('genres', models.CharField(blank=True, max_length=64, null=True)),
                ('actor_1_name', models.CharField(blank=True, max_length=27, null=True)),
                ('movie_title', models.CharField(blank=True, max_length=88, null=True)),
                ('num_voted_users', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('cast_total_facebook_likes', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('actor_3_name', models.CharField(blank=True, max_length=30, null=True)),
                ('facenumber_in_poster', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('plot_keywords', models.CharField(blank=True, max_length=149, null=True)),
                ('movie_imdb_link', models.CharField(blank=True, max_length=52, null=True)),
                ('num_user_for_reviews', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('content_rating', models.CharField(blank=True, max_length=9, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
                ('title_year', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('actor_2_facebook_likes', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('imdb_score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('aspect_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('movie_facebook_likes', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
            ],
            options={
                'db_table': 'movies',
                'managed': True,
            },
        ),
    ]
